### PR TITLE
feat: Add missing gradient functions

### LINKED ISSUE #773: enhancement: Radial Gradients
https://github.com/marc2332/freya/blob/1955629e6c355ff74415037e44869026da8aec89/crates/state/src/values/fill.rs#L15

### LINKED ISSUE #774: enhancement: Conic Gradient
https://github.com/marc2332/freya/blob/1955629e6c355ff74415037e44869026da8aec89/crates/state/src/values/fill.rs#L16

### PR DESCRIPTION
**Pull request by Aiving**
Closes #773, also closes #774

### CODE REVIEW

**Comment by Aiving** [comment]
@marc2332 I think it is now ready for workflow approval and, if all goes well, for review too.

**Review by marc2332 — CHANGES_REQUESTED** [review]
LGTM. Could you update the gradient example to showcase the new two methods tho?

**Comment by Aiving** [comment]
Oh, okay!

**Comment by Aiving** [comment]
> LGTM. Could you update the gradient example to showcase the new two methods tho?

done!

**Review by marc2332 — CHANGES_REQUESTED** [review]
I was thinking about having 1 example instead of 3 hehe

**Comment by Aiving** [comment]
> I was thinking about having 1 example instead of 3 hehe
done!

**Pull request merged**
