### PR TITLE
Create publishing chapter

### PR DESCRIPTION
**Pull request by tigerros**
This finishes the empty publishing chapter. `cargo-packager` is the tool used, but alternatives are mentioned.

### CODE REVIEW

**Comment by marc2332** [comment]
I will soon get back to https://github.com/marc2332/freya/pull/390, so maybe you can leave some reference in the docs?

**Comment by tigerros** [comment]
Sure. The link to the example doesn't work now though, because I changed the fork branch to the main branch. So #390 needs to be merged first (unless you're fine with a broken link...).

**Comment by marc2332** [comment]
It would be nice to also mention `winresource` in the instructions

the crate lets you apply a custom icon to the executable, I have updated the example with the new winresource usage 

https://github.com/marc2332/freya/pull/390/files#diff-814556d4ee71407537d0eebc7e55bb0a378c7948b755d02c0bf2ce62fb89dabf

**Comment by tigerros** [comment]
> It would be nice to also mention `winresource` in the instructions
> 
> the crate lets you apply a custom icon to the executable, I have updated the example with the new winresource usage
> 
> https://github.com/marc2332/freya/pull/390/files#diff-814556d4ee71407537d0eebc7e55bb0a378c7948b755d02c0bf2ce62fb89dabf

Doesn't `cargo-packager` do this?

**Comment by marc2332** [comment]
> > It would be nice to also mention `winresource` in the instructions
> > the crate lets you apply a custom icon to the executable, I have updated the example with the new winresource usage
> > https://github.com/marc2332/freya/pull/390/files#diff-814556d4ee71407537d0eebc7e55bb0a378c7948b755d02c0bf2ce62fb89dabf
> 
> Doesn't `cargo-packager` do this?

No, not for Windows. Installer icon != executable icon

**Comment by tigerros** [comment]
> > > It would be nice to also mention `winresource` in the instructions
> > > the crate lets you apply a custom icon to the executable, I have updated the example with the new winresource usage
> > > https://github.com/marc2332/freya/pull/390/files#diff-814556d4ee71407537d0eebc7e55bb0a378c7948b755d02c0bf2ce62fb89dabf
> > 
> > 
> > Doesn't `cargo-packager` do this?
> 
> No, not for Windows. Installer icon != executable icon

Sorry for not replying sooner. I looked at the examples and they don't use winresource, but the executables do have icons.

**Comment by marc2332** [comment]
> > > > It would be nice to also mention `winresource` in the instructions
> > > > the crate lets you apply a custom icon to the executable, I have updated the example with the new winresource usage
> > > > https://github.com/marc2332/freya/pull/390/files#diff-814556d4ee71407537d0eebc7e55bb0a378c7948b755d02c0bf2ce62fb89dabf
> > > 
> > > 
> > > Doesn't `cargo-packager` do this?
> > 
> > 
> > No, not for Windows. Installer icon != executable icon
> 
> Sorry for not replying sooner. I looked at the `cargo-packager` examples and they don't use winresource, but the executables do have icons (at least the tauri example, which is the most extensive one). I'm on Windows as well.

> Sorry for not replying sooner
it's fine, I wasn't expecting an answer right away

>  I looked at the `cargo-packager` examples and they don't use winresource, but the executables do have icons (at least the tauri example, which is the most extensive one). I'm on Windows as well.

I didn't test the Tauri one, I only tried the Dioxus one. If you install it, the app will not have an icon.

image

You can see the discord discussion around this [here](https://discord.com/channels/632194709351301132/1182089004506697808). I wasn't the one who came up with using `winresource`, they told me themself

**Comment by tigerros** [comment]
But...
image

**Comment by marc2332** [comment]
> But... image

The Tauri example doesn't apply here as it depends on tauri-build and Tauri's CLI.

**Comment by tigerros** [comment]
> > But... image
> 
> The Tauri example doesn't apply here as it depends on tauri-build and Tauri's CLI. It is Tauri who is changing the icon, not cargo-packager.

That makes sense. I don't mind `winresource`, I just don't like the fact that it's only for Windows, while Freya and `cargo-packager` are supposed to be cross-platform. Do you know of a cross-platform solution?

**Comment by marc2332** [comment]
> Also what discord server is that?
Open the link, it is the official CrabNebula Discord Server, authors of `cargo-packager`

**Comment by marc2332** [comment]
> > > But... image
> > 
> > 
> > The Tauri example doesn't apply here as it depends on tauri-build and Tauri's CLI. It is Tauri who is changing the icon, not cargo-packager.
> 
> That makes sense. I don't mind `winresource`, I just don't like the fact that it's only for Windows, while Freya and `cargo-packager` are supposed to be cross-platform. Do you know of a cross-platform solution?

The fact that the executable doesn't have an icon, only happens in Windows. Linux and MacOS is already handled by cargo-packager, you can read it in the conversation I had

**Comment by tigerros** [comment]
> > Also what discord server is that?
> 
> Open the link, it is the official CrabNebula Discord Server, authors of `cargo-packager`

It doesn't invite me automatically. Had to look for it on google.

> > > > But... image
> > > 
> > > 
> > > The Tauri example doesn't apply here as it depends on tauri-build and Tauri's CLI. It is Tauri who is changing the icon, not cargo-packager.
> > 
> > 
> > That makes sense. I don't mind `winresource`, I just don't like the fact that it's only for Windows, while Freya and `cargo-packager` are supposed to be cross-platform. Do you know of a cross-platform solution?
> 
> The fact that the executable doesn't have an icon, only happens in Windows. Linux and MacOS is already handled by cargo-packager, you can read it in the conversation I had

Ok I'll add it. Sorry for being maybe a little too stubborn

**Comment by marc2332** [comment]
> > > Also what discord server is that?
> > 
> > 
> > Open the link, it is the official CrabNebula Discord Server, authors of `cargo-packager`
> 
> It doesn't invite me automatically. Had to look for it on google.
> 
> > > > > But... image
> > > > 
> > > > 
> > > > The Tauri example doesn't apply here as it depends on tauri-build and Tauri's CLI. It is Tauri who is changing the icon, not cargo-packager.
> > > 
> > > 
> > > That makes sense. I don't mind `winresource`, I just don't like the fact that it's only for Windows, while Freya and `cargo-packager` are supposed to be cross-platform. Do you know of a cross-platform solution?
> > 
> > 
> > The fact that the executable doesn't have an icon, only happens in Windows. Linux and MacOS is already handled by cargo-packager, you can read it in the conversation I had
> 
> Ok I'll add it. Sorry for being maybe a little too stubborn

No worries.

**Comment by tigerros** [comment]
Hey, just letting you know that there's nothing else to add. I'm only saying this because you responded to the commits I made and I doubt you've been reviewing it for 11 hours :)

**Comment by marc2332** [comment]
> Hey, just letting you know that there's nothing else to add. I'm only saying this because you responded to the commits I made and I doubt you've been reviewing it for 11 hours :)

Don't worry, I add myself as reviewer, so I don't forget about it. I was working until just a few hours ago, so I'll check this asap

**Comment by tigerros** [comment]
> Don't worry, I add myself as reviewer, so I don't forget about it.

I know I was just confused since you replied with no notes and this is a very small change that barely needs a review. I thought you missed the fact that I made the commits and only saw the message... I didn't realize you could be at work :L

**Review by marc2332 — APPROVED** [review]
🔥 🔥 🔥 🔥

**Comment by marc2332** [comment]
Nice! Ty!

**Pull request merged**
