### PR TITLE
feat: Add `SortableTable` component

### PR DESCRIPTION
**Pull request by tigerros**
*Not sure if this exceeds the scope of the components library, but I don't really think so. Either way, I'm making it a draft PR because it's not polished (it is functional though), but feel free to leave some thoughts. And if this is beyond the scope of the components, I'll close it.*

Adds new component called `SortableTable`. It allows efficient (~200 micros with 10k rows 2 columns) and flexible sorting. I added an example in [`examples/sortable_table.rs`](https://github.com/tigerros/freya/blob/sortable-table/examples/sortable_table.rs). However, even a simple example is pretty verbose. Feel free to suggest improvements.

Also, why is `RefCell` cloned in freya? I use `std::cell::RefCell` in this PR, but maybe I should use the freya clone.

### CODE REVIEW

**Comment by marc2332** [comment]
> Also, why is RefCell cloned in freya? I use std::cell::RefCell in this PR, but maybe I should use the freya clone.

It's not Freya's clone, it's Dioxus's https://github.com/jkelleyrtp/debug-cell

**Comment by tigerros** [comment]
I searched for `RefCell` and the only other usage is in `animation.rs` which uses the std version. I'm guessing we don't need it.

**Comment by tigerros** [comment]
Hmm... I compared the performance with dioxus-desktop and freya is a lot worse... Any idea why? [Here](https://github.com/tigerros/dx-sortable-table) is my code. I built them in release mode and then ran the executables. Freya was slower when sorting and less responsive, e.g. the scrolling is very laggy even if the sort is finished.

**Comment by marc2332** [comment]
> I searched for `RefCell` and the only other usage is in `animation.rs` which uses the std version. I'm guessing we don't need it.

I would actually use dioxus's Refcell everywhere tbh, but it's fine for now

**Comment by marc2332** [comment]
> dioxus-desktop

I can't run the `dioxus-desktop` project, I get compile errors, can you make sure the code is up to date?

**Comment by tigerros** [comment]
Run `cargo build --release` instead of `dx bundle --release`

**Comment by marc2332** [comment]
> Hmm... I compared the performance with dioxus-desktop and freya is a lot worse... Any idea why? Is it just because of the styles? [Here](https://github.com/tigerros/dx-sortable-table) is my code. I built them in release mode and then ran the executables. Freya was slower when sorting and less responsive, e.g. the scrolling is very laggy even if the sort is finished.

For such long tables I would use VirtualizedScrollView instead btw

**Comment by marc2332** [comment]
> Run `cargo build --release` instead of `dx bundle --release`

I am already using cargo, the code is just missing, same happens with `freya`

**Comment by marc2332** [comment]
https://github.com/tigerros/dx-sortable-table/blob/master/freya/src/sortable_table.rs

https://github.com/tigerros/dx-sortable-table/blob/81612e8c765bb6772665254434335ee764843064/dioxus-desktop/src/sortable_table.rs#L1

**Comment by tigerros** [comment]
> For such long tables I would use VirtualizedScrollView instead btw

Ohh... that might be it :)

**Comment by tigerros** [comment]
> > Run `cargo build --release` instead of `dx bundle --release`
> 
> I am already using cargo, the code is just missing/wrong, same happens with `freya`

Weird. Should be good now.

**Comment by marc2332** [comment]
The thing here is that scrolling in Freya is implemented in "userland" as a component, this makes Dioxus have to rerun some components and diff some others, where in dioxus-desktop that's handled by the webview, so Dioxus doesn't even notice if you resize or scroll. Having this implemented in userland allows greater flexibility though, and for long lists VirtualizedScrollView is the way to go

**Comment by marc2332** [comment]
here it is with a quick swap from scrollview to virtual scroll view 
https://github.com/marc2332/freya/assets/38158676/17e37740-0baf-4f8d-83e9-bc9f25f12a0e

**Comment by tigerros** [comment]
Cool! Mind sharing the code?

**Comment by marc2332** [comment]
> Cool! Mind sharing the code?

`sortable_table.rs`:
```rs
use freya::prelude::*;
use std::cmp::Ordering;
use std::fmt::Display;
use std::cell::RefCell;

type Sorter<T> = Box<dyn Fn(&T, &T) -> Ordering>;

pub struct TableHeader<T, TTitle> where TTitle: Display {
    title: TTitle,
    sorter: Sorter<T>,
}

impl<T, TTitle> TableHeader<T, TTitle> where TTitle: Display {
    pub fn new(title: TTitle, sorter: Sorter<T>) -> Self {
        Self { title, sorter }
    }
}

pub struct SortableTable<T, TTitle> where TTitle: Display {
    pub headers: Vec<TableHeader<T, TTitle>>,
    pub rows: Vec<Vec<T>>,
}

impl<T, TTitle> SortableTable<T, TTitle> where TTitle: Display {
    pub fn new(headers: Vec<TableHeader<T, TTitle>>, rows: Vec<Vec<T>>) -> Self {
        Self { headers, rows }
    }

    pub fn sort_by_header(&mut self, header_index: usize, reverse_sort: bool) -> Result<(), String> {
        let Some(header) = self.headers.get(header_index) else {
            return Err(format!("the header at requested index {header_index} does not exist"));
        };

        let sorter = &header.sorter;

        self.rows.sort_by(|a, b| {
            let Some(cell_a) = a.get(header_index) else {
                return Ordering::Equal;
            };
            let Some(cell_b) = b.get(header_index) else {
                return Ordering::Equal;
            };
            if reverse_sort {
                sorter(cell_b, cell_a)
            } else {
                sorter(cell_a, cell_b)
            }
        });

        Ok(())
    }
}

#[derive(Props)]
pub struct SortableTableProps<T, TTitle> where TTitle: Display {
    pub table: RefCell<SortableTable<T, TTitle>>,
    pub default_order_direction: OrderDirection,
}

#[allow(non_snake_case)]
pub fn SortableTable<T: Clone, TTitle>(
    cx: Scope<SortableTableProps<T, TTitle>>,
) -> Element where T: Display, TTitle: Display {
    let current_header = use_state(cx, || 0);
    let table = &cx.props.table;
    let default_order_direction = &cx.props.default_order_direction;
    let order_direction = use_state(cx, || *default_order_direction);

    let on_header_click = |new_header_i: usize| {
        if *current_header.get() == new_header_i {
            if *order_direction.get() == OrderDirection::Up {
                order_direction.set(OrderDirection::Down);
            } else {
                order_direction.set(OrderDirection::Up);
            }
        } else {
            current_header.set(new_header_i);
            order_direction.set(*default_order_direction);
        }
    };

    if *order_direction.get() == OrderDirection::Down {
        table.borrow_mut().sort_by_header(*current_header.get(), false).unwrap();
    } else {
        table.borrow_mut().sort_by_header(*current_header.get(), true).unwrap();
    }

    let table_ref = table.borrow();

    render! {
        Table {
            columns: table_ref.headers.len(),
            TableHead {
                TableRow {
                    for (header_i, header) in table_ref.headers.iter().enumerate() {
                        TableCell {
                            key: "{header_i}",
                            order_direction: if *current_header.get() == header_i { Some(*order_direction.get()) } else { None },
                            onclick: move |_| on_header_click(header_i),
                            label {
                                header.title.to_string()
                            }
                        }
                    }
                }
            }
            TableBody {
                VirtualScrollView {
                    width: "100%",
                    height: "100%",
                    length: table_ref.rows.len(),
                    item_size: 25.0,
                    builder_values: table,
                    direction: "vertical",
                    builder: Box::new(|(_k, i, _cx, values)|{
                        let values = values.as_ref().unwrap();
                        let table = values.borrow();
                        let row = table.rows[i].clone(); // would be nice to not clone this here
                        rsx!(
                            TableRow {
                                key: "{i}",
                                for (cell_i, cell) in row.iter().enumerate() {
                                    TableCell {
                                        key: "{cell_i}",
                                        height: "25",
                                        label {
                                            width: "100%",
                                            "{cell}"
                                        }
                                    }
                                }
                            }
                        )
                    })
                }
            }
        }
    }
}

```

**Comment by tigerros** [comment]
Woah, that's instant! One thing though, the scrollbar dragging button disappears with smaller vertical window sizes even if I didn't scroll all the way up.

https://github.com/marc2332/freya/assets/76173380/9d432849-7596-4a89-828b-6ced5279c81d

**Comment by marc2332** [comment]
> Woah, that's instant! One thing though, the scrollbar dragging button in the top right disappears with smaller vertical window sizes even if I didn't scroll all the way up. Example:
> scrollbug.mp4

I have yet to add a minimum size for the thumb 😅

**Comment by marc2332** [comment]
What do you think about having this as a standalone crate? I was thinking we could move it to https://github.com/dioxus-community (I would invite you to the org), you can keep it in your account if you wan too, it's finet. Thoughts ? 👀

**Comment by tigerros** [comment]
I don't know... I'm not a huge fan of making a crate for just one component 😅 I feel like it's a relatively common use case without a super simple solution, which is why I made a PR here.

**Comment by marc2332** [comment]
Mmm, fair point!

**Comment by tigerros** [comment]
Hey @marc2332, I got around to making the API better (not polished, but usable). Most importantly, the order and amount of columns in each row is now type safe! The whole thing is also less verbose.

Now, there is something to note. This uses a flexible system that doesn't require `SortableTable` struct cells to implement anything. Instead, that is delegated to the `SortableTable` component. This is nice if we want to decouple the component and the struct, but it does have overhead. If we coupled the `SortableTable` struct and component cells to have the same constraints, it would be more efficient and simpler (if the user wanted to implement custom methods for the new `Row` trait, otherwise usage is similar in complexity). That might be better, but I got kinda focused on the flexible traits :P

Compare the examples:

<details>
<summary>Before</summary>

```rust
#[derive(PartialOrd, PartialEq, Eq)]
enum PersonColumn {
    Name(&'static str),
    Dollars(i64),
}

impl Ord for PersonColumn {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        match (self, other) {
            (PersonColumn::Name(s1), PersonColumn::Name(s2)) => s1.cmp(s2),
            (PersonColumn::Dollars(n1), PersonColumn::Dollars(n2)) => n1.cmp(n2),
            (PersonColumn::Name(_), PersonColumn::Dollars(_)) => std::cmp::Ordering::Equal,
            (PersonColumn::Dollars(_), PersonColumn::Name(_)) => std::cmp::Ordering::Equal,
        }
    }
}

impl Display for PersonColumn {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            PersonColumn::Name(name) => f.write_str(name),
            PersonColumn::Dollars(dollars) => f.write_str(&dollars.to_string()),
        }
    }
}

fn app(cx: Scope) -> Element {
    let headers = vec![
        SortableTableHeader::new("Name", Box::new(|a: &PersonColumn, b: &PersonColumn| a.cmp(b))),
        SortableTableHeader::new("Dollars", Box::new(|a: &PersonColumn, b: &PersonColumn| a.cmp(b))),
    ];

    let rows = vec![
        vec![PersonColumn::Name("John Smith"), PersonColumn::Dollars(120)],
        vec![PersonColumn::Name("Alice"), PersonColumn::Dollars(-81)],
        vec![PersonColumn::Name("John Doe"), PersonColumn::Dollars(18)],
        vec![PersonColumn::Name("Just made a bank account"), PersonColumn::Dollars(0)],
        vec![PersonColumn::Name("100 number guy 9"), PersonColumn::Dollars(1)],
        vec![PersonColumn::Name("Richie Rich"), PersonColumn::Dollars(999_999_999_999)],
        vec![PersonColumn::Name("Mose Schrute"), PersonColumn::Dollars(2)],
        vec![PersonColumn::Name("Michael Scott"), PersonColumn::Dollars(2500)],
        vec![PersonColumn::Name("Michael Scarn"), PersonColumn::Dollars(5000)],
        vec![PersonColumn::Name("Prison Mike"), PersonColumn::Dollars(-25000)],
        vec![PersonColumn::Name("Gavin Belson"), PersonColumn::Dollars(4_500_000_000)],
    ];

    let table = SortableTable::new(headers, rows);

    render!(
        SortableTable {
            table: RefCell::new(table),
            default_order_direction: OrderDirection::Down,
            alternate_colors: true,
        }
    )
}
```

</details>

<details>
<summary>After</summary>

```rust
impl_sortable_table_row! {
    pub struct Person {
        pub name: &'static str,
        pub dollars: i64,
    }
}

impl Display for PersonColumn {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            PersonColumn::Name(name) => f.write_str(name),
            PersonColumn::Dollars(dollars) => f.write_str(&dollars.to_string()),
        }
    }
}

impl Person {
    pub fn new(name: &'static str, dollars: i64) -> Self {
        Person { name, dollars }
    }
}

fn app(cx: Scope) -> Element {
    let rows = vec![
        Person::new("John Smith", 120),
        Person::new("Alice", -81),
        Person::new("John Doe", 18),
        Person::new("Just made a bank account", 0),
        Person::new("100 number guy 9", 1),
        Person::new("Richie Rich", 999_999_999_999),
        Person::new("Mose Schrute", 2),
        Person::new("Michael Scott", 2500),
        Person::new("Michael Scarn", 5000),
        Person::new("Prison Mike", -25000),
        Person::new("Gavin Belson", 4_500_000_000),
    ];

    let table = SortableTable::new(rows);

    render!(
        SortableTable {
            table: RefCell::new(table),
            default_sorted_column: PersonColumnPointer::Name,
            default_order_direction: OrderDirection::Down,
            alternate_colors: true,
        }
    )
}
```

</details>

**Pull request closed without merging**
