### PR TITLE
feat: Table component

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/marc2332/freya/issues/172

image

### CODE REVIEW

**Comment by fdncred** [comment]
I've been watching this from afar. I'm just looking for some gui toolkit to have a beautiful, easy to use, table/grid functionality. I'm not sure this will qualify, but I'm watching and hopefully it will.

My desired use case is to create a prototype table gui in nushell that allows you to do `ls | gridview` or `any | random | pipeline | gridview` in nushell and then it gathers the information and pops up a tabular gui window that allows you to do sorting. Really this would be for data exploration. Then maybe once that's working, we can add buttons or a toolbar to do other things.

Just sharing. Thanks!

**Comment by marc2332** [comment]
> I've been watching this from afar. I'm just looking for some gui toolkit to have a beautiful, easy to use, table/grid functionality. I'm not sure this will qualify, but I'm watching and hopefully it will.
> 
> My desired use case is to create a prototype table gui in nushell that allows you to do `ls | gridview` or `any | random | pipeline | gridview` in nushell and then it gathers the information and pops up a tabular gui window that allows you to do sorting. Really this would be for data exploration. Then maybe once that's working, we can add buttons or a toolbar to do other things.
> 
> Just sharing. Thanks!

hey Darren! 👋 

Thanks for the interest in Freya, I am a huge fan of Nushell 😄, I use it in both machines I have, and I love it :)) Thank you for your hard work 💪 

I just made a simple [JSON visualizer](https://github.com/marc2332/freya-visualizer) like you described, with Freya's new Table! Thoughts?? 😄 

image

**Comment by fdncred** [comment]
oh, wow @marc2332! That looks cool. I love it! I want to play with it more. Thanks so much for this quick example.

**Comment by fdncred** [comment]
wow, just compiled it. it's so cool to have an entry level app that I can tinker with. next up, make it work with `$nu | to json | freya-visualizer` or `sys | to json | freya-visualizer`, multi-level json. It's a good learning tool. Maybe think about whether this will work as a nushell plugin? Could we have it built into nushell as a feature? Not sure exactly, but json is an easy entry point. Great idea!

Like I said, the thing that I've been missing with the dozens of rust gui frameworks is just to ability to make beautiful tables, or even just beautiful guis of any type. It seems like so many frameworks focus on the api blah blah blah. Yes, that's important but it seems like most of these people forget about making a beautiful ui. No one wants to look at an ugly gui.  If someone points me to a way to easily make a beautiful ui, i'll make their api work.

**Comment by fdncred** [comment]
so fun! ok, i'll quit spamming your PR. LOL.
image

**Comment by marc2332** [comment]
> Maybe think about whether this will work as a nushell plugin

Oh! I haven't done any nushell plugin yet, but maybe it's possible! 🤔 

> Like I said, the thing that I've been missing with the dozens of rust gui frameworks is just to ability to make beautiful tables, or even just beautiful guis of any type. It seems like so many frameworks focus on the api blah blah blah. Yes, that's important but it seems like most of these people forget about making a beautiful ui. No one wants to look at an ugly gui. If someone points me to a way to easily make a beautiful ui, i'll make their api work.

I completely agree on this one, one of the main things I wanted is to have a Table where you can compose the UI instead of just dumping the whole data into a component with some weird configuration parameters. The current Table components are not very customizable yet, but I plan on adding themes. Also, nothing stops devs from replacing certain components of the Table with their own, it's very flexible

**Pull request merged**
