### PR TITLE
feat: set window size with `use_platform`

### PR DESCRIPTION
**Pull request by mingshuisheng**
add set window size function for UsePlatform.
example
```rust
let platform = use_platform();
platform.set_window_size(Size2D::new(800.0, 400.0));
```

### CODE REVIEW

**Review by marc2332 — CHANGES_REQUESTED** [review]
Could you also make it work in `freya-testing`? Let me know if you need guidance, although I think it should be pretty straighforward

**Comment by mingshuisheng** [comment]
> Could you also make it work in `freya-testing`? Let me know if you need c, although I think it should be pretty straighforward

Yep, i need guidance.

**Comment by marc2332** [comment]
> > Could you also make it work in freya-testing? Let me know if you need guidance, although I think it should be pretty straighforward
> 
> Yep, i need guidance.

You simply need to add:

```rs
EventMessage::SetWindowSize(size) => {
    self.config.size = size;
}
```

to `test_handler.rs` in L136

**Comment by mingshuisheng** [comment]
> > > Could you also make it work in freya-testing? Let me know if you need guidance, although I think it should be pretty straighforward
> > 
> > 
> > Yep, i need guidance.
> 
> You simply need to add:
> 
> ```rust
> EventMessage::SetWindowSize(size) => {
>     self.config.size = size;
> }
> ```
> 
> to `test_handler.rs` in L136

Thank you for your help. I thought I needed to call `platform.set_window_size` somewhere.

**Review by marc2332 — CHANGES_REQUESTED** [review]
Could you add an example showing how to use it? 😄

**Comment by marc2332** [comment]
There also appear to be some conflicts

**Comment by marc2332** [comment]
Closing due to inactivity and also because its not needed anymore as freya now has the with_window method

**Pull request closed without merging**
