### PR TITLE
feat: React to scale factor changes

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/marc2332/freya/issues/270
depends on https://github.com/marc2332/freya/pull/598

WIP

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
Works great! Tho the `massive` example look differently on different scale.

On scale factor 1:
Screenshot 2024-05-10 at 7 58 29 PM

On scale factor 2:
Screenshot 2024-05-10 at 7 58 42 PM

**Comment by marc2332** [comment]
oh, I probably missed some parameter to scale :D

Was it like that before?

**Comment by ZeroX-DG** [comment]
This is how it looks on main:

Scale factor 1:
Screenshot 2024-05-10 at 8 13 53 PM

Scale factor 2:
Screenshot 2024-05-10 at 8 14 05 PM

**Comment by marc2332** [comment]
Yeah, main looks good, I probably missed something on this PR :)

**Comment by marc2332** [comment]
@ZeroX-DG That was actually not working well on main either, and it was because of a wrong usage of `calc()` in the massive.rs example, which I just fixed. Should work fine now :)

**Comment by ZeroX-DG** [comment]
Nice! Works like a charm now!

**Pull request merged**
