### PR TITLE
fix: React to scale factor changes

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/marc2332/freya/issues/1

### CODE REVIEW

**Comment by marc2332** [comment]
Could you try this PR @trickypr please 🙏 ? I am not sure if this fix will help, let's see

**Comment by trickypr** [comment]
It still sorta small....
Screen Shot 2023-03-11 at 7 40 17 pm

**Comment by marc2332** [comment]
> It still sorta small.... Screen Shot 2023-03-11 at 7 40 17 pm

Alright, I will see what I can do, thank you :D

**Comment by marc2332** [comment]
Closed in favor of https://github.com/marc2332/freya/pull/146

**Pull request closed without merging**
